language: node_js
node_js:
  - 11

before_script:
  - npm install -g node-gyp
  - npm install

script:
  - npm run test

jobs:
  include:
    - stage: test
      script: ./src/__tests__/integrations.test

